Game logic
rOluochKe/tictactoe pull request #3
Opened 2019-09-11 17:16 UTC by rOluochKe

2019-09-11 20:09 UTC, AdnanAfsari requested changes
Hello @rOluochKe @AndresFMoya ✋ 

Nice try guys but you have to make some changes and improve your game.Please check my comments on those files and below and submit for another review after making changes.

- [x] I was trying to play the game in my local machine and i got this error.please make sure its working.
<img width="1276" alt="Screenshot 2019-09-12 at 1 56 02 AM" src="https://user-images.githubusercontent.com/8613710/64730159-80da0980-d500-11e9-8dca-6c1fe041b17e.png">

- [x] we can make our README.md more descriptive for example adding instructions how to play the game etc, you can check other project for inspiration.

Note: Please  add a short summary of changes in Pull Request description 😄.

Happy Coding

2019-09-11 20:09 UTC, AdnanAfsari commented on bin/main.rb
>  ttt.show_instructions
Its better to keep everything within the class.

2019-09-11 20:09 UTC, AdnanAfsari commented on lib/board.rb
> +  def show
User interaction commands should be in one executable file main.rb

2019-09-11 20:09 UTC, AdnanAfsari commented on lib/board.rb
> +  def show_instructions
User interaction commands should be in one executable file main.rb

2019-09-11 20:09 UTC, AdnanAfsari commented on lib/player.rb
> +  # rubocop: disable Naming/UncommunicativeMethodParamName
Its not a good idea disabling linter, you better fix those errors to maintain standard code 😸

2019-09-11 21:20 UTC, AndresFMoya commented on lib/player.rb
> +  # rubocop: disable Naming/UncommunicativeMethodParamName
Hello Adnan. Thanks for your review. Now We don't know how to solve the cyclomatic and perceived complexity errors. Could you please point us the right address. Thanks!

2019-09-11 22:28 UTC, Oghenebrume50 commented
reviewing...

2019-09-11 23:46 UTC, Oghenebrume50 requested changes
`Welcome to terminal tic tac toe!
The following are the move positions you are able to make:
|tl|tc|tr|
|ml|mc|mr|
|bl|bc|br|

It's Player x's turn.
j
| | | |
| | | |
| | | |
It's Player y's turn.
r
| | | |
| | | |
| | | |
It's Player x's turn.
3
| | | |
| | | |
| | | |
It's Player y's turn.
4
| | | |
| | | |
| | | |
It's Player x's turn.
5
| | | |
| | | |
| | | |
It's Player y's turn.
2
| | | |
| | | |
| | | |
It's Player x's turn.
1
| | | |
| | | |
| | | |
It's Player y's turn.
9
| | | |
| | | |
| | | |
It's Player x's turn.
8
| | | |
| | | |
| | | |
It's Player y's turn.
0
| | | |
| | | |
| | | |
It's Player x's turn.
-
| | | |
| | | |
| | | |
It's Player y's turn.
2
| | | |
| | | |
| | | |
It's Player x's turn.
4
| | | |
| | | |
| | | |
It's Player y's turn.
5
| | | |
| | | |
| | | |
It's Player x's turn.
6
| | | |
| | | |
| | | |
It's Player y's turn.
7
| | | |
| | | |
| | | |
It's Player x's turn.
8
| | | |
| | | |
| | | |
It's Player y's turn.
5
| | | |
| | | |
| | | |
It's Player x's turn.
6
| | | |
| | | |
| | | |
It's Player y's turn.
7
| | | |
| | | |
| | | |
It's Player x's turn.
8
| | | |
| | | |
| | | |
It's Player y's turn.
9
| | | |
| | | |
| | | |
It's Player x's turn.
6
| | | |
| | | |
| | | |
It's Player y's turn.
4
| | | |
| | | |
| | | |
It's Player x's turn.
1
| | | |
| | | |
| | | |
It's Player y's turn.
2
| | | |
| | | |
| | | |
It's Player x's turn.
3
| | | |
| | | |
| | | |
It's Player y's turn.
4
| | | |
| | | |
| | | |
It's Player x's turn.
5
| | | |
| | | |
| | | |
It's Player y's turn.
7
| | | |
| | | |
| | | |
It's Player x's turn.
8
| | | |
| | | |
| | | |
It's Player y's turn.
9
| | | |
| | | |
| | | |
It's Player x's turn.
tl
|x| | |
| | | |
| | | |
It's Player y's turn.
tm
|x| | |
| | | |
| | | |
It's Player x's turn.
tc
|x|x| |
| | | |
| | | |
It's Player y's turn.
tr
|x|x|y|
| | | |
| | | |
It's Player x's turn.
bm
|x|x|y|
| | | |
| | | |
It's Player y's turn.
bc
|x|x|y|
| | | |
| |y| |
It's Player x's turn.
bl
|x|x|y|
| | | |
|x|y| |
It's Player y's turn.
br
|x|x|y|
| | | |
|x|y|y|
It's Player x's turn.
mc
|x|x|y|
| |x| |
|x|y|y|
It's Player y's turn.
ml
|x|x|y|
|y|x| |
|x|y|y|
It's Player x's turn.
mr
|x|x|y|
|y|x|x|
|x|y|y|
It's Player y's turn.
tm
|x|x|y|
|y|x|x|
|x|y|y|`

This is an output from an attempted play of the game, I believe we can make it more user-friendly, by outputting a warning on wrong input, and as you can see the game did not end properly, after a draw.

[NOTE]: In OOP generally, modules are for objects that you need to use once, for example the Board can be a module but not the player because the player is needed more than once, we need two instances of a player

[IMPORTANT] please separate the logic from the display code, things like puts, print, chomp should be in one final and only that file
this is an OOP project so we want to use OOP concepts and methodology. 
Each object should be in it's own class, for example,  player, board and game  could be in seperate classes. 

Think about atributes and behaviours, what are the behaviours of an object, these are the likely methods needed, the attributes are the characteristics, in a human it would be things like hand, leg, eye. In a Player it could be name, symbol, etc. 

Read about single responsibility principle and DRY

2019-09-11 23:51 UTC, Oghenebrume50 requested changes
**Please fix these things and request for a re-review** :pray: 

oh and do not forget to fix linter issues too

2019-09-11 23:51 UTC, Oghenebrume50 commented on lib/player.rb
> +  end
read about DRY, and as a note on single responsibility, it is not the job of the player to determine who won the game, the game should be smart enough to do that :smile:

2019-09-17 21:34 UTC, maelfosso requested changes
Hello Coders,

# Really good job :+1:  It's was a pleasure to review it.

Everything is good but only one thing to change: **No puts, gets.chomp and print** into `lib/`

Kindly, delete all the **puts, gets.chomp and print** into classes `lib/player.rb` and `lib/game.rb`
Then re-submit a code review request
Thanks

2019-09-18 01:51 UTC, Ispirett commented
# Reviewing

2019-09-18 02:33 UTC, Ispirett approved these changes
Very Good job Folks its a thumbs up from me :+1: 
![image](https://user-images.githubusercontent.com/38801423/62908290-41739e00-bd45-11e9-922f-6b7cf52979ee.png)

I suggest adding a more descriptive readme!.

2019-09-18 02:33 UTC, Ispirett commented on bin/main.rb
> +class Playgame
Convention for a class name is every new word should begin with a capital letter eg: `PlayGame`

2019-09-18 15:14 UTC, merged